namespace: default
configMapGenerator:
- name: efs-provisioner-configs
  literals:
  - fileSystemId=fs-c7a94d0d
  - efsRegion=eu-west-1
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- pod-security-policy.yaml
- service-account.yaml
- storage-class.yaml
vars:
- name: EFS_FILE_SYSTEM_ID
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: efs-provisioner-configs
  fieldref:
    fieldpath: data.fileSystemId
- name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: efs-provisioner-configs
  fieldref:
    fieldpath: data.efsRegion
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: efs-provisioner-configs
  fieldref:
    fieldpath: metadata.namespace
configurations:
- varreference.yaml
